kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: node-red-{{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: ceph-rbd
