replicaCount: 1
image:
  repository: justinbarrick/node-red
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: nodered
  type: ClusterIP
  externalPort: 80
  internalPort: 1880
ingress:
  enabled: true
  host: nodered.codesink.net
  annotations:
    kubernetes.io/ingress.class: nginx
  cert: cert-nodered-codesink-net
nodeSelector:
  beta.kubernetes.io/arch: amd64
resources:
  limits:
    cpu: 0.2
    memory: 256Mi
  requests:
    cpu: 0.1
    memory: 128Mi
