replicaCount: 1
image:
  repository: justinbarrick/node-red
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: nodered
  type: ClusterIP
  externalPort: 80
  internalPort: 1880
ingress:
  enabled: true
  host: nodered.codesink.net
  annotations:
    kubernetes.io/ingress.class: nginx
    external-dns.alpha.kubernetes.io/target: nginx-ingress.codesink.net.
    ingress.kubernetes.io/auth-tls-verify-client: "on"
    ingress.kubernetes.io/auth-tls-secret: "node-red/cloudflare"
  cert: codesink-origin-ca
resources:
  limits:
    cpu: 0.2
    memory: 256Mi
  requests:
    cpu: 0.1
    memory: 128Mi
